$(document).ready(function(){
    $("#menu").hover(function(){
      $(this).stop().animate({
        left:"0px"
      },450,"easeInSine");
    },function(){
      $(this).stop().animate({
        left:"-128px"
      },900,"easeOutBounce");
    });
});