$(document).ready(function(){
    $("#menu").hover(function(){
      $(this).stop().animate({
        top:"0px"
      },450,"easeInSine");
    },function(){
      $(this).stop().animate({
        top:"-60px"
      },900,"easeOutBounce");
    });
});